nginx:
    image: nginx:latest
    ports:
        - '38180:80'
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./wordpress:/var/www/html
    links:
        - wordpress
    restart: always

mysql:
    image: mariadb
    ports:
        - '33306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=pass
    restart: always

wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    ports:
        - '19000:9000'
    volumes:
        - ./wordpress:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=wpdb
        - WORDPRESS_TABLE_PREFIX=prefixe_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=pass
    links:
        - mysql
    restart: always